// Include this instead of <Box2D/Box2D.h> to minimize warnings generated by named file(s)
#pragma once
#pragma warning	(push)
#pragma warning	(disable : 4930 26495 26812)
#include	<Box2D/Box2D.h>
#pragma warning	(pop)	//#pragma warning (default : 4930 26495 26812)